version: '3'

services:
  order-db:
    image: postgres:11.9
    volumes:
      - order-db-data:/var/lib/postgresql/data/
    networks:
      - kafka
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  order:
    image: kafka-order:latest
    ports:
      - 8080:8080
    networks:
      - kafka
    depends_on:
      - order-db
      - kafka
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:tracing:postgresql://order-db:5432/admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  stock-db:
    image: postgres:11.9
    volumes:
      - stock-db-data:/var/lib/postgresql/data/
    networks:
      - kafka
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5433:5432

  stock:
    image: quay.io/puzzle/microservices-lab-kafka-stock:latest
    ports:
      - 8081:8080
    networks:
      - kafka
    depends_on:
      - stock-db
      - kafka
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:tracing:postgresql://stock-db:5432/admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - 3000:3000
    networks:
      - kafka
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus:v2.25.0
    ports:
      - 9090:9090
    networks:
      - kafka
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    networks:
      - kafka
    volumes:
      - ./config/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    networks:
      - kafka
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 16686:16686

volumes:
  order-db-data:
  stock-db-data:

networks:
  kafka:
    driver: bridge
    ipam:
      driver: default
